### ISSUE TITLE
I got some error with running train_val_FCN_Da.py .

### ISSUE THREAD

**Issue by Dasona** [YangZhang4065/AdaptationSeg#3]
I did set data path folder and .h5 file.
When I ran train_val_FCN_DA.py code , I got this error.

Using Theano backend.
/home/tf/anaconda2/lib/python2.7/site-packages/keras/layers/core.py:633: UserWarning: `output_shape` argument not specified for layer output and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 22, 320, 640)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
/home/tf/anaconda2/lib/python2.7/site-packages/keras/layers/core.py:633: UserWarning: `output_shape` argument not specified for layer output_2 and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 22, 320, 640)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
Start loading files
Start training
Epoch 1/60
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/tf/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/tf/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/tf/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 612, in data_generator_task
    generator_output = next(self._generator)
  File "train_val_FCN_DA.py", line 144, in myGenerator
    tar_idx=sample(range(len(cityscape_im_generator)),target_batch_size)
  File "/home/tf/anaconda2/lib/python2.7/random.py", line 323, in sample
    raise ValueError("sample larger than population")
ValueError: sample larger than population

Traceback (most recent call last):
  File "train_val_FCN_DA.py", line 203, in <module>
    seg_model.fit_generator(myGenerator(),callbacks=[Validate_on_CityScape()], steps_per_epoch=steps_per_epoch, epochs=60)
  File "/home/tf/anaconda2/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/home/tf/anaconda2/lib/python2.7/site-packages/keras/engine/training.py", line 1877, in fit_generator
    str(generator_output))
ValueError: output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: None

**Comment by YangZhang4065** [comment]
Did you organize your CityScape image/segmentation annotation folder correctly as marked in the readme? It looks like that the data loader is unable to correctly find the images in the path.
